
#The goal is to annotate the AT-hook motifs of Human HMGAs
#HMGA1 (Uniprot ID P17096 ) and HMGA2 (Uniprot ID P52926)

install.packages("ggplot2")
install.packages("ggseqlogo")


library(ggplot2)
library(ggseqlogo)

#Human HMGA1_2_AT-hooks (Hu_HMGA1_2_ATH)
#Human HMGA1 AT-hooks (Hu_HMGA1_ATH)
#Human HMGA2 AT-hooks (Hu_HMGA1_ATH)
#Human HMGA AT-hook1 (Hu_HMGA_ATH1)
#Human HMGA AT-hook2 (Hu_HMGA_ATH2)
#Human HMGA AT-hook3 (Hu_HMGA_ATH3)

seqs_ATH <- list(Hu_HMGA1_2_ATH <- c("TEKRGRGRPRKQ", "TPKRPRGRPKGS", "TPGRKPRGRPKK", 
                                     "PQKRGRGRPRKQ", "SPKRPRGRPKGS", "TGEKRPRGRPRK"),
                 Hu_HMGA1_ATH <- c("TEKRGRGRPRKQ", "TPKRPRGRPKGS", "TPGRKPRGRPKK"),
                 Hu_HMGA2_ATH <- c("PQKRGRGRPRKQ", "SPKRPRGRPKGS", "TGEKRPRGRPRK"),
                 Hu_HMGA_ATH1<- c("TEKRGRGRPRKQ", "PQKRGRGRPRKQ"),
                 Hu_HMGA_ATH2 <- c("TPKRPRGRPKGS", "SPKRPRGRPKGS"),
                 Hu_HMGA_ATH3 <- c("TPGRKPRGRPKK", "TGEKRPRGRPRK"))

ggseqlogo(seqs_ATH, method = 'prob', ncol=3)

############################################################

#Hu_DBD2
seq_dbd2_hu <- c("TPKRPRGRPKGSKNKGAA", "SPKRPRGRPKGSKNKSPS")
ggseqlogo(seq_dbd2_hu, method = 'prob')

seq_dbd1_hu <-c("TEKRGRGRPRKQPPVSPGT", "TPGRKPRGRPKKLEKEEEE", "PQKRGRGRPRKQQQEPTGE", "TGEKRPRGRPRKWPQQVVQ")
ggseqlogo(seq_dbd1_hu, method = 'prob')
############################################################
# Poaceae HMGAs Clade 1_a (3ATH)Seq Logo for AT hooks
SeqATH_C1_a <- list(C1_a_ATH1 <- c("DAPDAPPKRGRGRPRKPIDPNAPP", "DAPDAPPKRGRGRPRKPIDPNAPP", "DAPDAPPKRGRGRPRKPIDPNAPP", 
                                   "DAPDAPPKRGRGRPPKSKDPNAPP", "PPPKPSSPRPRGRPPKSSSVSDAP"),
                    C1_a_ATH2 <- c("PPPKSASPRPRGRPAKPKDPEAEA", "APPKPASPRPRGRPVKPKDPEAEA", "APPKPASPRPRGRPTKPKDPEAEA", 
                                   "PKPKPASPRPRGRPSKPKDPEAQQ", "SSSVSDAPKSRGRPPKKAKTAAAP"),
                    C1_a_ATH3 <- c("PAVDGSAKRGRGRPPKARPAEPAA", "PAVDGSAKRGRGRPPKARPAEPAA", "PAVDGSAKRGRGRPPKARPAEPAA",
                                   "ADGSAPVKRGRGRPPKVRPAEPAA", "GDGSAPAKRGRGRPPKVRAAVQPS"),
                    C1_a_ATHall <- c("DAPDAPPKRGRGRPRKPIDPNAPP", "DAPDAPPKRGRGRPRKPIDPNAPP", "DAPDAPPKRGRGRPRKPIDPNAPP", 
                                     "DAPDAPPKRGRGRPPKSKDPNAPP", "PPPKPSSPRPRGRPPKSSSVSDAP", "PPPKSASPRPRGRPAKPKDPEAEA", 
                                     "APPKPASPRPRGRPVKPKDPEAEA", "APPKPASPRPRGRPTKPKDPEAEA", "PKPKPASPRPRGRPSKPKDPEAQQ",
                                     "SSSVSDAPKSRGRPPKKAKTAAAP", "PAVDGSAKRGRGRPPKARPAEPAA", "PAVDGSAKRGRGRPPKARPAEPAA", 
                                     "PAVDGSAKRGRGRPPKARPAEPAA", "ADGSAPVKRGRGRPPKVRPAEPAA", "GDGSAPAKRGRGRPPKVRAAVQPS"))      
ggseqlogo(SeqATH_C1_a, method = 'prob', ncol=2)

############################################################
# Poaceae HMGAs Clade 1_b (4ATH)Seq Logo for AT hooks

SeqATH_C1_b <- list(C1_b_ATH1 <- c("DAPDAPPKRGRGRPPKARDPGAPV", "DAPDAPPKRGRGRPPKARDPNAPP", "GAPDAPPKRGRGRPPKARDPNAPA",
                                   "DAPDAPPKRGRGRPPKPRDPNAPP", "DDPTLPPKRGRGRPPKAKDAATAP", "DDPSLPPKRGRGRPPKPKDAAAAA"),
                    C1_b_ATH2 <- c("APVSPPSGRGRGRPPKPKDPLDAA", "SPASAGTGRGRGRPPKAKSALDAA", "PKSPSSTGRGRGRPPKAKSPLEAA", 
                                   "PPPKPSSPRPRGRPPKSKDPISDA", "APDTVSSPRGRGRPPKPKDPVAEA", "AAPAASSPRPRGRPPKPKDPLAEA"), 
                    C1_b_ATH3 <- c("KQATAGMPRARGRPPKKAKTEGGA", "KQATAGMPKARGRPPKKAKTSEDG", "KQATAGMPKPRGRPPKKAKTDGAA", 
                                   "DPISDAIPKSRGRPPKKAKTAPAP", "AKATVGMPRARGRPPKKAKVDQEA", "AKATSGMPRARGRPPKKAKVEQED"), 
                    C1_b_ATH4 <- c("GDGSTPVKRGRGRPPKVRPVVPSE", "GDGSTPVKRGRGRPPKVRPVVPSE", "GDGSTPGKRGRGRPPKVRPAVPSE", 
                                   "GDGSAPVKRGRGRPPKVRPAVPSE", "AAAAAPVKRGRGRPPKVRPAAEPA", "AEAAPPVKRGRGRPPKVRPAAPVG"), 
                    C1_b_ATH_all <- c("DAPDAPPKRGRGRPPKARDPGAPV", "DAPDAPPKRGRGRPPKARDPNAPP", "GAPDAPPKRGRGRPPKARDPNAPA", 
                                      "DAPDAPPKRGRGRPPKPRDPNAPP", "DDPTLPPKRGRGRPPKAKDAATAP", "DDPSLPPKRGRGRPPKPKDAAAAA", 
                                      "APVSPPSGRGRGRPPKPKDPLDAA", "SPASAGTGRGRGRPPKAKSALDAA", "PKSPSSTGRGRGRPPKAKSPLEAA", 
                                      "PPPKPSSPRPRGRPPKSKDPISDA", "APDTVSSPRGRGRPPKPKDPVAEA", "AAPAASSPRPRGRPPKPKDPLAEA", 
                                      "KQATAGMPRARGRPPKKAKTEGGA", "KQATAGMPKARGRPPKKAKTSEDG", "KQATAGMPKPRGRPPKKAKTDGAA", 
                                      "DPISDAIPKSRGRPPKKAKTAPAP", "AKATVGMPRARGRPPKKAKVDQEA", "AKATSGMPRARGRPPKKAKVEQED", 
                                      "GDGSTPVKRGRGRPPKVRPVVPSE", "GDGSTPVKRGRGRPPKVRPVVPSE", "GDGSTPGKRGRGRPPKVRPAVPSE", 
                                      "GDGSAPVKRGRGRPPKVRPAVPSE", "AAAAAPVKRGRGRPPKVRPAAEPA", "AEAAPPVKRGRGRPPKVRPAAPVG"))

ggseqlogo(SeqATH_C1_b, method = 'prob', ncol=2)
############################################################
# Poaceae HMGAs Clade 2 (4ATH)Seq Logo for AT hooks
SeqATH_C2 <- list(C2_ATH1 <- c("APSATPAKRGRGRPPKDPNAPPKP", "SDAPAPPKRGRGRPPKPKDPNAPP", "AVSATPAKRGRGRPPKDPNAPPKP", 
                               "APSATPAKRGRGRPPKDPNAPPKP", "APSATPAKRGRGRPPKDPNAPPKP", "APSATPAKRGRGRPPKDPNAPPKP"), 
                  C2_ATH2 <- c("PKDPNTPKRGRGRPPKAKDPMADA", "ARDPNAPKRGRGRPPKPKDPNAPP", "KPDPNTPKRGRGRPPKDPMSVAVK", 
                               "PKDPNTPKRGRGRPPKAKDSMADA", "PKDPNTPKRGRGRPPKVKDPMADA", "PKDPNTPKRGRGRPPKAKDPMADA"), 
                  C2_ATH3 <- c("AKATTGMPRGRGRPPGPSSAKKAK", "APKAKAPKRGRGRPPKTDKATSSP", "AKATTGMPKGRGRPPGPSAAKKAK", 
                               "AKATTGMPRGRGRPPGPSSAKKAK", "AKATTGMPRGRGRPPGPSSAKKVK", "AKATTGMPRGRGRPPGPSSAKKAK"), 
                  C2_ATH4 <- c("ADGSAPAKRGRGRPRKVAVXXXXX", "PSGAAPAKRGRGRPPKVRAXXXXX", "ASGSAPAKRGRGRPRKVAAXXXXX", 
                               "ASGSAPAKRGRGRPRKVAAXXXXX", "GSGSAPAKRGRGRPRKVAVXXXXX", "ADGSAPAKRGRGRPRKVAVXXXXX"), 
                  c2_ATHs <- c("APSATPAKRGRGRPPKDPNAPPKP", "SDAPAPPKRGRGRPPKPKDPNAPP", "AVSATPAKRGRGRPPKDPNAPPKP", 
                               "APSATPAKRGRGRPPKDPNAPPKP", "APSATPAKRGRGRPPKDPNAPPKP", "APSATPAKRGRGRPPKDPNAPPKP", 
                               "PKDPNTPKRGRGRPPKAKDPMADA", "ARDPNAPKRGRGRPPKPKDPNAPP", "KPDPNTPKRGRGRPPKDPMSVAVK", 
                               "PKDPNTPKRGRGRPPKAKDSMADA", "PKDPNTPKRGRGRPPKVKDPMADA", "PKDPNTPKRGRGRPPKAKDPMADA", 
                               "AKATTGMPRGRGRPPGPSSAKKAK", "APKAKAPKRGRGRPPKTDKATSSP", "AKATTGMPKGRGRPPGPSAAKKAK", 
                               "AKATTGMPRGRGRPPGPSSAKKAK", "AKATTGMPRGRGRPPGPSSAKKVK", "AKATTGMPRGRGRPPGPSSAKKAK", 
                               "ADGSAPAKRGRGRPRKVAVXXXXX", "PSGAAPAKRGRGRPPKVRAXXXXX", "ASGSAPAKRGRGRPRKVAAXXXXX", 
                               "ASGSAPAKRGRGRPRKVAAXXXXX", "GSGSAPAKRGRGRPRKVAVXXXXX", "ADGSAPAKRGRGRPRKVAVXXXXX"))
ggseqlogo(SeqATH_C2, method = 'prob', ncol=2)


############################################################
# Poaceae HMGAs Clade 3 Seq Logo for AT hooks

SeqATH_C3 <- list(C3_ATH1 <- c("TKRGRGRPPKPKDPVAEG", "TKRGRGRPPKPKDPVAEG"),
                  C3_ATH2 <- c("VKRGRGRPPKPKNPVAED", "VKRGRGRPPKPKNPVAED", "VKRGRGRPPKPKVAVAED"),
                  C3_ATH3 <- c("VKRGRGRPPKPKDTITVA", "VKRGRGRPPKLKDPINVA", "AKRGRGRPPKPKDPAAMG"),
                  C3_ATH4 <- c("RGRGRGRPPKKAKVAVED", "SPRGRGRPPKKAKVAVED", "MLSPRGRPPKKTKVEEAP"),
                  C3_ATH5 <- c("VKRGRGRPPKVRPAVVGA", "VKRGRGRPPRXXXXXXXX", "VKRGRGRPPKVKHXXXXX"),
                  C3_ATH_all <- c("TKRGRGRPPKPKDPVAEG", "TKRGRGRPPKPKDPVAEG", 
                                  "VKRGRGRPPKPKNPVAED", "VKRGRGRPPKPKNPVAED", "VKRGRGRPPKPKVAVAED",
                                  "VKRGRGRPPKPKDTITVA", "VKRGRGRPPKLKDPINVA", "AKRGRGRPPKPKDPAAMG",
                                  "RGRGRGRPPKKAKVAVED", "SPRGRGRPPKKAKVAVED", "MLSPRGRPPKKTKVEEAP",
                                  "VKRGRGRPPKVRPAVVGA", "VKRGRGRPPRXXXXXXXX", "VKRGRGRPPKVKHXXXXX"))
ggseqlogo(SeqATH_C3, method = 'prob', ncol=2)

##########################################################
#Human HMGAs


SeqATH_Hu <- list(Hu_ATH1 <- c("QEKDGTEKRGRGRPRKQPPVSPGT", "PAAPAPQKRGRGRPRKQQQEPTGE"),
                  Hu_ATH2 <- c("PSEVPTPKRPRGRPKGSKNKGAAK", "PTGEPSPKRPRGRPKGSKNKSPSK"),
                  Hu_ATH3 <- c("KTTTTPGRKPRGRPKKLEKEEEEG", "KAEATGEKRPRGRPRKWPQQVVQK"),  
                  Hu_ATH_all <- c("QEKDGTEKRGRGRPRKQPPVSPGT", "PAAPAPQKRGRGRPRKQQQEPTGE", 
                                  "PSEVPTPKRPRGRPKGSKNKGAAK", "PTGEPSPKRPRGRPKGSKNKSPSK", 
                                  "KTTTTPGRKPRGRPKKLEKEEEEG", "KAEATGEKRPRGRPRKWPQQVVQK"))

ggseqlogo(SeqATH_Hu, method = 'prob', ncol=2)



##########################################################
#For ATH motif analysis 10 aa on either side of the RGRP invariant repeat were selected
#For ATH5 motifs 'X' was used when there were no AA available to complete 10 residues after RGRP 
SeqATH_C3 <- list(C3_ATH1 <- c ("DVNPVPTKRGRGRPPKPKDPVAEG", "DVNPVHTKRGRGRPPKPKDPVAEG"),
                  C3_ATH2 <- c ("DAAAGPVKRGRGRPPKPKVAVAED", "DAAAMPVKRGRGRPPKPKNPVAED", "AAAAVPVKRGRGRPPKPKNPVAED"),
                  C3_ATH3 <- c ("DAVAGPAKRGRGRPPKPKDPAAMG", "DANAVPVKRGRGRPPKPKDTITVA", "DGNAVPVKRGRGRPPKLKDPINVA"), 
                  C3_ATH4 <- c ("AWATSGMLSPRGRPPKKTKVEEAP", "MLSPRGRGRGRGRPPKKAKVAVED", "ATSGMLSPRGRGRPPKKAKVAVED"),
                  C3_ATH5 <- c ("PSTDVPVKRGRGRPPKVKHXXXXX", "DASAVPVKRGRGRPPKVRPAVVGA", "DASAVHVKRGRGRPPRXXXXXXXX"),
                  C3_ATH_all <- c("DVNPVPTKRGRGRPPKPKDPVAEG", "DVNPVHTKRGRGRPPKPKDPVAEG", "DAAAGPVKRGRGRPPKPKVAVAED", 
                                  "DAAAMPVKRGRGRPPKPKNPVAED", "AAAAVPVKRGRGRPPKPKNPVAED", "DAVAGPAKRGRGRPPKPKDPAAMG", 
                                  "DANAVPVKRGRGRPPKPKDTITVA", "DGNAVPVKRGRGRPPKLKDPINVA", "AWATSGMLSPRGRPPKKTKVEEAP", 
                                  "MLSPRGRGRGRGRPPKKAKVAVED", "ATSGMLSPRGRGRPPKKAKVAVED", "PSTDVPVKRGRGRPPKVKHXXXXX", 
                                  "DASAVPVKRGRGRPPKVRPAVVGA", "DASAVHVKRGRGRPPRXXXXXXXX"))

ggseqlogo(SeqATH_C3, method = 'prob', ncol=2)



#################################################
#h1_h5 DOMAIN OF POACEAE


Poaceae_H1H5 <- c ("SYPEMILEAIEALDDKNGSNKTAISQYIEAKHEG-LPPAHSSLLTAHLARMKQTGELAFSKN",
                   "SYPEMILAAIEALDDRNGSNKTAISQHIEGKYEGLLPPAHPSLLTAHLARMKQTGELAFSKN",
                   "SYPEMILAAIAALNDKNGSNKSAISKHIEGKYG-DLPKEHAALLTAHLVRMKETGQLLFLKN",
                   "PYPEMILAAIAALNDKNGSNKSAISKHIEGKYG-DLPKEHAALLTAHLVRMKESGQLLFLKN",
                   "PYPEMILAAIAALNDKNGSNKSAISKYIEGKYG-DLPKEHGALLTAHLVRMKESGQLFFLKN",
                   "PYPEMILEAIEALNDKQGSNKSAISKHIEGKYG-DLPPAHGSLLTAHLSRMKESGELLFLKN",
                   "PYPEMILAAIEGLNEKSGSNKSAISKFIEGKYG-DLPPAHASLLTAHLARMKESGELIFLKN",
                   "PYPEMILAAIEGLGDKNGSNKSAISKFIEDKYG-ELPPAHASLLTAHLARMKESGELIFLKN",
                   "PYPEMILAAIEALNDKNGSNKSAISKFIEGKYG-DLPPAHASLLTAHLARMKESGELILPRD",
                   "PYPEMILAAIEGLDDKSGSNKSAISKYIEGKYG-SLPPAHASLLTAHLARMKESGELVFLKN",
                   "PYPEMILAAIEDLGDKSGSNKSAISRYIEGKYDGDLPPAHASLLAAHLARMKESGELVFVKN",
                   "PYPEMILAAIEALGDKNGSSKSAISSYIEEKYE-GLPSAHASLLTANLASMKEAGKLAFVKN",
                   "PYPEMILAAIEALGDKNGSSKSAISSYIEEKYE-GLPSAHASLLTANLASMKEAGKLAFVKN",
                   "PYPEMIIAAIEALGDKNGSSKSAISSYIEEKYE-GLPSAHASLLTANLASMKEAGKLAFVKN",
                   "PYPEMILAAIEALGDKNGSSKSAISSYIEEKYE-GLPSAHASLLTANLASMKEAGKLAFAKN",
                   "PYPEMILAAIEALGDTNGSNKSAISSYIEEKYE-GLPSAHASLLTANLASMKEAGKLAFVKN",
                   "TYPDMILEAIDALDDKNGANKTAISSFIEEKYK-ELPSAHASLLTANLASMKESGKLLFDKN",
                   "SYPEMIVEAIRALGLEVSSNKTAISDYIRGRYGSSLPAQHNAFLTGHLARMKATGELAFLRN",
                   "SYPEMIVEAIRALGLENGCNKTAISDYIKGSYGSNLPAQHNAVLTGHLARMKATGELAFLRN",
                   "SYSEMILEAIDALDNANGSNKTAISGYLKNKCRASLPSDHTSLLTINLGRMKSSGELVFARN")
ggseqlogo(Poaceae_H1H5, method = 'prob')








